---
- name: Apply Kubernetes Configuration after making changes
  hosts: node
  become: yes
  tasks:
    - name: Create and update Deployment
      command: kubectl apply -f /home/user/Deployment.yml
      register: deployment_result
      environment:
        KUBECONFIG: /home/user/.kube/config
      ignore_errors: yes

    - name: Create New Service
      command: kubectl apply -f /home/user/Service.yml
      register: service_result
      environment:
        KUBECONFIG: /home/user/.kube/config
      ignore_errors: yes

